### ISSUE TITLE
BUG027: Not able to get optimizer object when a session failed on replay status and the worker was relaunched

### ISSUE THREAD

**Issue by sebcb1** [sebcb1/Carnica#72]

**Comment by sebcb1** [comment]
Traceback (most recent call last):
  File "/home/sebastien/dev/Carnica/website/website/drivers/globalDriver.py", line 21, in wrapper
    return function(*args, **kwargs)
  File "/home/sebastien/dev/Carnica/website/website/drivers/globalDriver.py", line 246, in backupConfig
    self.driver.backupConfig(backup_optimizer)
  File "/home/sebastien/dev/Carnica/website/website/drivers/baseDriver.py", line 343, in backupConfig
    opt = backup_optimizer[self.ts]
KeyError: <Tunningsessions: ts_MYDB>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sebastien/dev/Carnica/website/website/coreEngine.py", line 204, in startSerial
    driver.backupConfig(self.backup_optimizer)
  File "/home/sebastien/dev/Carnica/website/website/drivers/globalDriver.py", line 28, in wrapper
    raise ErrorDriver(600, e)
website.drivers.baseDriver.ErrorDriver

**Comment by sebcb1** [comment]
Status en erreur: BACKING UP CURRENT CONFIG
